araon/blog/routes.py
from araon.code.routes import post
from flask import Blueprint, render_template, url_for,redirect,request
from araon.models import bloginfo
from datetime import datetime
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy import create_engine



blog = Blueprint('blog',__name__,template_folder="templates",static_url_path='/blog/static',static_folder='static')



engine = create_engine('sqlite:///araon/site.db')

Session = scoped_session(sessionmaker(bind=engine))

@blog.route('/blog')
def bloghome():
    posts = bloginfo.query.order_by(bloginfo.date_posted.desc()).all()
    return render_template('blogHome.html', posts = posts)

@blog.route('/blog/about')
def about():
    return render_template('blogAbout.html')


@blog.route('/blog/post/<int:post_id>')
def post(post_id):
    post = bloginfo.query.filter_by(id=post_id).one()
    return render_template('blogPost.html', post=post, prev = post_id - 1, nex = post_id + 1)



@blog.route('/blog/supersecretlinktoaddpost')
def add():
    return render_template('blogadd.html')



@blog.route('/blog/addblogpost', methods=['POST'])
def addblogpost():

    session = Session()

    title = request.form['title']
    subtitle = request.form['subtitle']
    author = request.form['author']
    content = request.form['ckeditor']
    header = request.form['header_img']

    post = bloginfo(title=title, sub_title = subtitle, author=author, content=content, date_posted=datetime.now(), header_img = header)

    session.add(post)
    session.commit()

    return redirect("/blog/supersecretlinktoaddpost")

araon/blog/templates/blogAbout.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>A Cup of Reality | About</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/vendor.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/main.css')}}">

    <!-- script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/modernizr.js')}}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

</head>

<body class="ss-bg-white">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div id="top" class="s-wrap site-wrapper">

        <!-- site header
        ================================================== -->
        <header class="s-header header">

            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="/blog">
                        <img src="{{url_for('blog.static', filename='images/logo.svg')}}" alt="A Cup of Reality">
                    </a>
                </div>

                <!-- toggles -->
                <a href="#0" class="header__menu-toggle"><span>Menu</span></a>

            </div>

            <nav class="header__nav-wrap">

                <ul class="header__nav">
                    <li><a href="/blog" title="">Home</a></li>
                    <li class="current"><a href="/blog/about" title="">About</a></li>
                </ul> <!-- end header__nav -->


            </nav> <!-- end header__nav-wrap -->

        </header> <!-- end s-header -->


        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    <div class="media-wrap">
                        <div>
                            <img src="{{url_for('blog.static', filename='images/about.png')}}"  alt="well this is a shame">
                        </div>
                    </div>

                    <div class="content__page-header">
                        <h1 class="display-1">Hi! there
                        </h1>
                    </div> <!-- end content__page-header -->
                    

                    <h2>Who am I?</h2>
                    <p>
                        
                        I’m just a dude who decided to make a website to document his life. I’m not all that special, successful, interesting, or brilliant, though others say otherwise. (They would.) 
                        I was not prompted to challenge myself academically as a pupil. I did what was required to get a top mark and no more; grades were all that mattered, however arbitrary they may be. 
                        I did not partake in extracurriculars besides sports—which I was encouraged to pursue, against all sensible logic, despite being perpetually among the tallest of my class. Sports are where young men (and women) attempt to destroy other young men (and women) for no reason other than machismo and school spirit and sports.
                        I was not constituted for the endeavor, and even if I was, I’d still feel the repercussions of battle.
                    </p>
                    <p>
                        I was a ghost through college, which I attended absentmindedly and virtually compulsorily with no intentions or prudence other than to take the easiest courses possible and involve myself no more than physically or mentally required.
                        Well The competition i was avoiding for so long in sport resurfaced as a dogfight for grade points, cutthroat educational warfare.
                    </p>
                    <p>
                        So: Hi. <b>I’m Araon.</b> My full name is Soumik Ghosh, but I go by Araon for short. Araon has a nice ring. You’ll probably remember it.
                    </p>
                    <p>
                        I was raised in Sodpure, West Bengal, a middle-class suburb of Kolkata. It floods during the rainy seasons, the local playgrounds are good, and most young residents don’t realize how good they have it. Opportunity’s overwhelming. <br>
                        I spent my teens absorbed in trivial, introverted pursuits that hindered my ability to speak up and as a result I feel I’m behind the bar. I fear I will ever catch up.
                    </p>
                    
                    <h2>Why I Blog</h2>
                    <p><b>To change.</b>This is nothing more than a mirror. It reflects whatever’s been gunked in my mind and impossible to fully grasp otherwise. 
                        The stretches during which I’ve not regularly divulged my running thoughts, through this medium or another, have been the most sclerotic and self-oblivious of my life.
                    </p>
                    <p>
                        Sometimes i'll have guest posts by some of my friends, they'll give a diffrent theme, concept and god forbid even an opinion
                        on things on and around the world
                    </p>
                    <div class="entry__thumb">
                        <blockquote>
                            <p>Life becomes real fun once you realize you can build anything you want</p>

                            <cite>Devon Crawford</cite>
                        </blockquote>
                    </div>
                    <h2>Credits</h2>
                    <p>All images are taken from <a href="https://unsplash.com/">Unsplash</a> or from my own collection.</p>
                    <hr>
                    
                    </div>
                    
                </section>
            </main>

        </div> <!-- end s-content -->


        <!-- footer
        ================================================== -->
        <footer class="s-footer footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                        <span>© Copyright Araon</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Back to Top" href="#top"></a>
            </div>
        </footer>

    </div> <!-- end s-wrap -->


    <!-- Java Script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/jquery-3.2.1.min.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/plugins.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/main.js')}}"></script>

</body>

araon/blog/templates/blogHome.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>A Cup of Reality</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/vendor.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/main.css')}}">

    <!-- script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/modernizr.js')}}"></script>


</head>

<body>

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div id="top" class="s-wrap site-wrapper">

        <!-- site header
        ================================================== -->
        <header class="s-header">

            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="/blog">
                        <img src="{{url_for('blog.static', filename='images/logo.svg')}}" alt="A Cup of Reality">
                    </a>
                </div>

                <!-- toggles -->
                <a href="#0" class="header__menu-toggle"><span>Menu</span></a>

            </div> 

            <nav class="header__nav-wrap">

                <ul class="header__nav">
                    <li class="has-children">
                        <a href="#0" title="">Recent Posts</a>
                        <ul class="sub-menu">
                            {% for post in posts%}
                            <li><a href="{{ url_for('blog.post', post_id=post.id) }}">○ {{ post.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="/blog/about" title="">About</a></li>
                </ul> 


            </nav> 

        </header> 

        <div class="s-content">
            <div class="masonry-wrap">
                <div class="masonry">
                    <div class="grid-sizer"></div>
                    {% for post in posts %}
                    <article class="masonry__brick entry format-standard animate-this">
                        <div class="entry__thumb">
                            <a href="{{ url_for('blog.post', post_id=post.id) }}" class="entry__thumb-link">
                                <img src="{{ post.header_img }}" alt="">
                            </a>
                        </div>
                        <div class="entry__text">
                            <div class="entry__header">
                                <a href="{{ url_for('blog.post', post_id=post.id) }}">
                                <h2 class="entry__title">{{ post.title }}</h2>
                                </a>
                                <div class="entry__meta">
                                    <span class="entry__meta-cat">
                                       <p>{{ post.author}}</p>
                                    </span>
                                    <span class="entry__meta-date">
                                        <p>{{ post.date_posted.strftime('%B %d, %Y') }}</p>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endfor %}

                    

                </div> <!-- end masonry -->
            </div> <!-- end masonry-wrap -->
        </div> <!-- end s-content -->
 <!-- end entry__pagenav -->


        <!-- footer
        ================================================== -->
        <footer class="s-footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                        <span>© Copyright Araon</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Back to Top" href="#top"></a>
            </div>
        </footer>

    </div> <!-- end s-wrap -->


    <!-- Java Script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/jquery-3.2.1.min.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/plugins.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/main.js')}}"></script>

</body>

araon/blog/templates/blogPost.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>A Cup of Reality | {{ post.title}}</title>
    <meta name="author" content="{{ post.author }}">
    <meta name="description" content="{{ post.sub_title }}"> 
    <meta property="og:image" content= "{{ post.header_img }}">
    <meta property="og:type"  content="article" />

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/vendor.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/main.css')}}">

    <!-- script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/modernizr.js')}}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

</head>

<body class="ss-bg-white">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div id="top" class="s-wrap site-wrapper">

        <!-- site header
        ================================================== -->
        <header class="s-header header">

            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="/blog">
                        <img src="{{url_for('blog.static', filename='images/logo.svg')}}" alt="A Cup of Reality">
                    </a>
                </div>

                <!-- toggles -->

                <a href="#0" class="header__menu-toggle"><span>Menu</span></a>

            </div>

            <nav class="header__nav-wrap">

                <ul class="header__nav">
                    <li><a href="/blog" title="">Home</a></li>
                    <li><a href="/blog/about" title="">About</a></li>
                </ul> <!-- end header__nav -->

            </nav> <!-- end header__nav-wrap -->

        </header> <!-- end s-header -->


        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <article class="column large-full entry format-standard">

                    <div class="media-wrap entry__media">
                    </div>

                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                        {{ post.title }}
                        </h1>
                        <ul class="entry__header-meta">
                            <li class="author">By <a>{{ post.author }}</a></li>
                            <li class="date">{{ post.date_posted.strftime('%B %d, %Y') }}</li>
                        </ul>
                    </div> <!-- end entry__header -->

                    <div class="entry__content">

                        <h3><i>{{ post.sub_title }}</i></h3>

                        <br>

                        <p>{{ post.content | safe }}</p>


                    </div> <!-- end entry content -->
                    <div class="entry__pagenav">
                        <div class="entry__nav">
                            <div class="entry__prev">
                                <a href="{{ prev }}" rel="prev">
                                    Previous Post
                                </a>
                            </div>
                            <div class="entry__next">
                                <a href="{{ nex }}" rel="next">
                                    Next Post 
                                </a>
                            </div>
                        </div>
                    </div>


                </article> <!-- end column large-full entry--> 

            </main>

        </div> <!-- end s-content -->




        <!-- footer
        ================================================== -->
        <footer class="s-footer footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                        <span>Oh wait</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Back to Top" href="#top"></a>
            </div>
        </footer>

    </div> <!-- end s-wrap -->


    <!-- Java Script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/jquery-3.2.1.min.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/modernizr.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/main.js')}}"></script>

</body>

araon/blog/templates/blogadd.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>A Cup of Reality - Add Post</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/vendor.css')}}">
    <link rel="stylesheet" href="{{url_for('blog.static', filename='css/main.css')}}">

    <!-- script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/modernizr.js')}}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

        <!-- ckeditor
    ================================================== -->

    {{ ckeditor.load() }}

</head>

<body class="ss-bg-white">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div id="top" class="s-wrap site-wrapper">

        <!-- site header
        ================================================== -->
        <header class="s-header header">

            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="/">
                        <img src="{{url_for('blog.static', filename='images/logo.svg')}}" alt="A Cup of Reality">
                    </a>
                </div>
                <!-- toggles -->
                <a href="#0" class="header__menu-toggle"><span>Menu</span></a>

            </div>

            <nav class="header__nav-wrap">

                <ul class="header__nav">
                    <li><a href="/blog" title="">Home</a></li>
                    <li><a href="/blog/about" title="">About</a></li>
                </ul> <!-- end header__nav -->


            </nav> <!-- end header__nav-wrap -->

        </header> <!-- end s-header -->


        <!-- site content
        ================================================== -->
        <div class="s-content content">
            <main class="row content__page">
                
                <section class="column large-full entry format-standard">

                    <h3 class="h2">Add Post</h3>
        
                    <form name="contactForm" id="contactForm" method="post" action="/blog/addblogpost" autocomplete="off">
                        <fieldset>
    
                            <div class="form-field">
                                <input name="title" id="title" class="full-width" placeholder="Title" value="" type="text">
                            </div>

                            <div class="form-field">
                                <p>Image URL</p>
                                <input name="header_img" id="header_img" class="full-width" placeholder="Image URL" value="https://source.unsplash.com/1080x1920/?blog" type="text">
                            </div>
    
                            <div class="form-field">
                                <input name="subtitle" id="subtitle" class="full-width" placeholder="Subtitle" value="" type="text">
                            </div>
    
                            <div class="form-field">
                                <input name="author" id="author" class="full-width" placeholder="Author Name" value="" type="text">
                            </div>
    
                            <div class="message form-field">
                                <h4>Blog Body</h4>
                                {{ ckeditor.create() }}
                            </div>
    
                            <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large full-width" value="Post" type="submit">
    
                        </fieldset>
                    </form> <!-- end form -->

                </section>

            </main>

        </div> <!-- end s-content -->


        <!-- footer
        ================================================== -->
        <footer class="s-footer footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                        <span>© 2post or !2post is the question</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Back to Top" href="#top"></a>
            </div>
        </footer>

    </div> <!-- end s-wrap -->


    <!-- Java Script
    ================================================== -->
    <script src="{{url_for('blog.static', filename='js/jquery-3.2.1.min.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/plugins.js')}}"></script>
    <script src="{{url_for('blog.static', filename='js/main.js')}}"></script>
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>

</body>