araon/code/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length


class LoginForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

araon/code/routes.py
from flask import Blueprint, render_template, url_for,redirect,request
from araon.models import blogPost
from araon.code.forms import LoginForm
from datetime import datetime
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy import create_engine


code = Blueprint('code',__name__,template_folder="templates",static_url_path='/code/static',static_folder='static')


engine = create_engine('sqlite:///araon/site.db')
Session = scoped_session(sessionmaker(bind=engine))


@code.route('/code')
def codehome():
    posts = blogPost.query.order_by(blogPost.date_posted.desc()).all()
    return render_template('index.html', posts=posts)

@code.route('/code/about')
def about():
    return render_template('about.html')


@code.route('/code/post/<int:post_id>')
def post(post_id):
    post = blogPost.query.filter_by(id=post_id).one()
    return render_template('post.html', post=post,  prev = post_id -1)

@code.route('/code/supersecretlinktoaddpost')
def add():
    return render_template('add.html')


@code.route('/code/addcodepost', methods=['POST'])
def addcodepost():

    session = Session()

    title = request.form['title']
    subtitle = request.form['subtitle']
    author = request.form['author']
    content = request.form['ckeditor']
    header = request.form['header_img']

    post = blogPost(title=title, sub_title = subtitle, author=author, content=content, date_posted=datetime.now(), header_img = header)

    session.add(post)
    session.commit()

    return redirect("/code")

araon/code/templates/about.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>While True: - About me</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('code.static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('code.static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('code.static', filename='clean-blog.min.css') }}" rel="stylesheet">
    <style>
      .txt-type > .txt {
            border-right: 0.2rem solid rgb(255, 255, 255);
        }
      .body {
        overflow: hidden;
      }
    </style>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/">[Araon]</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/code">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/code/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('code.static', filename='about.png') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1><span class="txt-type" data-wait="1000" data-words='["Hello traveller","নমস্কর পথিক","नमस्ते यात्री","こんにちは","안녕하세요 여행자","مرحبا المسافر"]'></span></h1>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <h2> HI!, I'm <i> Soumik</i>,</h2>
          <span>Final year Computer Science Engineering student at Hooghly Engineering and Technology College, Kolkata.<br>
          The purpose of this blog would be to document my thoughts and rants about all things code and computers.</span>
          <p>I’ve been programing since High School, teaching myself whatever necessary to achieve desired technological ends (for my other <a href="https://github.com/Araon">personal projects</a> and this <a href="/">website</a>) along the way. My forte lies in backend code that controls the output of elements; design work gives me the fantods, but I am capable of fiddling frontend to the point where the product looks OK.
             If it needs to be done, I will figure it out... <i>somehow</i></p>
          <h3>What’s with the name?</h3>
          <span> I've been always facinated by the <i>While loop</i>. I know it is weird but can you imagine, a task , that has no end, running forever and ever...
          <br>
          also there is a pretty sweet game on steam with the same name.</span>
          <p></p>
          <iframe src="https://store.steampowered.com/widget/619150/" frameborder="0" width="646" height="190"></iframe>
          <p></p>

          <h3>Credits</h3>
          <span> All images are taken from <a href="https://unsplash.com/">Unsplash</a> or from my own collection.</span>
        </div>
        
      </div>
      
    </div>


    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <hr>
            <p class="copyright text-muted">This blog is maintained by <a href="https://github.com/Araon">Araon</a></p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('code.static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='popper.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='bootstrap.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('code.static', filename='clean-blog.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='typingeffect.js')}}"></script>

  </body>

</html>

araon/code/templates/add.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    

    <title>Add Post</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('code.static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('code.static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('code.static', filename='clean-blog.min.css') }}" rel="stylesheet">

    {{ ckeditor.load() }}

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/">While True:</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/code">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/code/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('code.static', filename='post-bg.jpg') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Add Post</h1>
              <span class="subheading">You can create a blog post here.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <form name="addForm" id="addForm" method="POST" action="/code/addcodepost" novalidate>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="text" class="form-control" placeholder="Title" name="title" id="title" required data-validation-required-message="Please enter a title.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Subtitle</label>
                <input type="text" class="form-control" placeholder="Subtitle" name="subtitle" id="subtitle" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Author</label>
                <input type="text" class="form-control" placeholder="Author" name="author" id="author" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Background Image</label>
                <input type="text" class="form-control" placeholder="Background Image Url" name="header_img" id="header_img" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Blog Content</label>
                {{ ckeditor.create() }}
                <input type="submit">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-secondary" id="sendMessageButton">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Araon 2021</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('code.static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='popper.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='bootstrap.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('code.static', filename='clean-blog.min.js') }}"></script>
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>

  </body>

</html>

araon/code/templates/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>While True:</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('code.static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('code.static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('code.static', filename='clean-blog.min.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/code">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/code/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ url_for('code.static', filename='home-bg.jpg') }}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>While True:</h1>
              <span class="subheading"><h5> A place to document and ramble about code</h5></span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in posts %}
          <div class="post-preview">
            <a href="{{ url_for('code.post', post_id=post.id) }}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                {{ post.sub_title }}
              </h3>
            </a>
            <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
          </div>
          {% endfor %}
          <hr>
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">This Blog is maintained by <a href="https://github.com/Araon">Araon</a></p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('code.static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='popper.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='bootstrap.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('code.static', filename='clean-blog.min.js') }}"></script>

  </body>

</html>

araon/code/templates/post.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>While True: | {{ post.title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('code.static', filename='bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('code.static', filename='font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ url_for('code.static', filename='clean-blog.min.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="/">While True:</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/code">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/code/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ post.header_img }}'); background-color:#0d0d0d;">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="subheading">{{ post.sub_title }}</h2>
              <span class="meta">Posted by
                {{ post.author }}
                on {{ post.date_posted.strftime('%B %d, %Y') }}</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->


    <hr>

    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.content|safe }}
          </div>
        </div>
      </div>
    </article>

    <hr>

    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <h2 class="subheading"><a href='{{ prev }}'>Previous Post</a></h2>
          </div>
        </div>
      </div>
    </article>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">The blog is maintained by <a href="https://github.com/Araon">Araon</a></p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('code.static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='popper.min.js') }}"></script>
    <script src="{{ url_for('code.static', filename='bootstrap.min.js') }}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{ url_for('code.static', filename='clean-blog.min.js') }}"></script>

  </body>

</html>